version: '2'

services:
  balancer:
    image: nginx:1.25-alpine-slim
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    #network_mode: "host"
    #depends_on:
    #  - python_app
  python_app:
    #hostname: pyapp
    build: target_python_service
    #ports:
    #  - "8081:8081"